### PR TITLE
v14-rc2c

### LINKED ISSUE #38: Testing branch update.
Hey, can we get release candidate 2 on testing branch?

### PR DESCRIPTION
**Pull request by lapineige**
https://codeberg.org/calckey/calckey/releases/tag/v14.0.0-rc2c

Fix #38 

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
> 649732 INFO DEBUG - packages/backend build:  56 | import { fetchMeta } from "@/misc/fetch-meta.js";
649732 INFO DEBUG - packages/backend build:  57 |
649732 INFO DEBUG - packages/backend build:  58 | const logger = apLogger;
649732 INFO DEBUG - packages/backend build:     `----
649732 INFO DEBUG - packages/backend build: Caused by:
649732 INFO DEBUG - packages/backend build:     Syntax Error
649732 INFO DEBUG - packages/client build: vite v4.3.9 building for production...
649732 INFO DEBUG - packages/backend build: Successfully compiled: 865 files, copied 21 files with swc (253.79ms)
649732 INFO DEBUG - packages/backend build: Failed to compile 1 file with swc.
649733 INFO DEBUG - packages/backend build: Error: Failed to compile:
649733 INFO DEBUG - packages/backend build: src/remote/activitypub/models/note.ts
649733 INFO DEBUG - packages/backend build:     at initialCompilation (/var/www/calckey/node_modules/.pnpm/@swc+cli@0.1.62_@swc+core@1.3.62_chokidar@3.5.3/node_modules/@swc/cli/lib/swc/dir.js:163:19)
649733 INFO DEBUG - packages/backend build:     at async dir (/var/www/calckey/node_modules/.pnpm/@swc+cli@0.1.62_@swc+core@1.3.62_chokidar@3.5.3/node_modules/@swc/cli/lib/swc/dir.js:228:5)
649733 INFO DEBUG - packages/backend build: Failed


@ThatOneCalculator could that be an upstream issue ?

**Comment by ThatOneCalculator** [comment]
This is a known upstream issue with the tag, and why I recommend on the release notes to just use the beta branch.

**Comment by oufmilo** [comment]
> This is a known upstream issue with the tag, and why I recommend on the release notes to just use the beta branch.

it's better to wait for the final version

**Comment by lapineige** [comment]
I knew it :smile:

**Comment by ThatOneCalculator** [comment]
Gotta love codeberg refusing to let me fix my tags 🙃🙃🙃

**Pull request closed without merging**
