### PR TITLE
v13.1.4.1

### PR DESCRIPTION
**Pull request by lapineige**
https://codeberg.org/calckey/calckey/releases/tag/v13.1.4.1

### CODE REVIEW

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
According to CI https://ci-apps-dev.yunohost.org/ci/job/5588 :

```
475138 INFO DEBUG - + sudo -u calckey env PATH=/opt/node_n/n/versions/node/19/bin:/opt/node_n/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin NODE_ENV=production pnpm build
475138 INFO DEBUG -
475138 INFO DEBUG - > calckey@13.1.3-rc build /var/www/calckey
475138 INFO DEBUG - > pnpm -r run build && pnpm run gulp
475138 INFO DEBUG -
475138 INFO DEBUG - Scope: 3 of 4 workspace projects
475139 INFO DEBUG - packages/client build$ pnpm vite build
475139 INFO DEBUG - packages/sw build$ pnpm swc src -d built -D
475139 INFO DEBUG - packages/backend build$ pnpm swc src -d built -D
475139 INFO DEBUG - packages/client build: undefined
475139 INFO DEBUG - packages/client build:  ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL  Command failed with ENOENT: vite build
475139 INFO DEBUG - packages/client build: spawn vite ENOENT
475139 INFO DEBUG - packages/client build: Failed
475139 INFO DEBUG - undefined
475139 INFO DEBUG - /var/www/calckey/packages/client:
475139 INFO DEBUG -  ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  client@ build: `pnpm vite build`
475140 INFO DEBUG - Exit status 1
475140 INFO DEBUG -  ELIFECYCLE  Command failed with exit code 1.
475140 INFO DEBUG - + ynh_exit_properly
```

> packages/client build:  ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL  Command failed with ENOENT: vite build

I don't understand the sudden issue.
I don't know if it's a pnpm bug or something (https://github.com/pnpm/pnpm/issues/4146) or an error in our side.
@ThatOneCalculator do you have any clue ? Is there any particular change on Calckey side ? 🤔

**Comment by ThatOneCalculator** [comment]
Nothing was changed on our side.

**Comment by lapineige** [comment]
Ok thanks.

Maybe a pnpm update that fails the whole thing ? :thinking: I don't understand how it works. What's that `vite build` step ? :thinking:

**Comment by ThatOneCalculator** [comment]
Why would you run `pnpm update`? That's to update internal packages :/

**Comment by lapineige** [comment]
Closed by mistake (thanks Github UX)

**Comment by lapineige** [comment]
!testme

**Comment by ThatOneCalculator** [comment]
v13.1.4.1 has been released with a hotfix

**Comment by lapineige** [comment]
Running CI again just in case, but we still have this (pnpm ?) that will probably fail it :(

I don't understand the issue.

**Comment by lapineige** [comment]
!testme

**Comment by oufmilo** [comment]
#30 solved

**Pull request closed without merging**
