### PR TITLE
Test

### PR DESCRIPTION
**Pull request by oufmilo**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by oufmilo** [comment]
!testme

**Comment by lapineige** [comment]
!testme

**Comment by oufmilo** [comment]
ça va être la catastrophe je n'y ai pas remis les pieds depuis que j'ai créé le projet.

**Comment by lapineige** [comment]
C'est là pour exploser en vol :)
Je veux voir ce que ça donne avec ta dernière modification :)

**Comment by lapineige** [comment]
La dernière erreur:
```
sudo -u calckey env PATH=/opt/node_n/n/versions/node/16.15.0/bin:/opt/node_n/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin NODE_ENV=production yarn build
yarn run v1.22.19
yarn workspaces foreach run build && yarn run gulp
error Invalid subcommand. Try "info, run"
```

**Comment by lapineige** [comment]
So it fails here : https://github.com/YunoHost-Apps/calckey_ynh/blob/master/scripts/install#L135
With a mysterious result…

To be honest I don't understand why this command is ran, and not `rebuild` as stated here : https://codeberg.org/calckey/calckey#git-pull-and-run-these-steps-to-update-calckey-in-the-future, and why it uses this complicated (and faulty ?) PATH

**Comment by lapineige** [comment]
Oh ok thanks for merging, but I was working on it meanwhile :sweat_smile:

**Comment by lapineige** [comment]
Oh I see this is the command from Misskey documentation : https://misskey-hub.net/en/docs/install/manual.html#_5-build-misskey

There is nothing like this for Calckey ?

And I don't know how we can debug such an unhelpful error message…

@ThatOneCalculator maybe you could have some clue here ?

**Comment by ThatOneCalculator** [comment]
https://codeberg.org/calckey/calckey#getting-started

**Comment by ThatOneCalculator** [comment]
Also, I don't see anywhere in your build file `corepack enable` being run...

**Comment by ericgaspar** [comment]
@lapineige sorry, but I think mentionning this PR did closed it automatically when I have merged #1570

**Comment by lapineige** [comment]
Ok thanks for your feedback. I don't feel it's a big deal, at least now #4 is partly solved :)

**Comment by lapineige** [comment]
> https://codeberg.org/calckey/calckey#getting-started

Yes, but the "build and launch" section is empty. I don't know what we are supposed to do here.

**Pull request merged**
