### PR TITLE
v14.0.0-rc3

### PR DESCRIPTION
**Pull request by lapineige**
https://codeberg.org/calckey/calckey/releases/tag/v14.0.0-rc3

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
I will test this on my server before merging to Testing.

**Comment by benborges** [comment]
What do I have to do to help testing ? 
I'm running current package version 13.1.4.1

**Comment by lapineige** [comment]
@oufmilo could you merge it please ? :)

**Comment by lapineige** [comment]
@benborges : run the command `yunohost app upgrade calckey  -u https://github.com/lapineige/calckey_ynh/tree/patch-1` to upgrade to this branch / RC3.
It will make a backup, but anyway make sure you can cancel the operation afterwards if it fails with that backup.

Then tell us if it's working as expected :slightly_smiling_face:

**Comment by benborges** [comment]
I tested with yunohost app upgrade calckey -u https://github.com/lapineige/calckey_ynh/tree/testing
>Info: Now upgrading calckey...
>Success! calckey is already up-to-date
>Success! Upgrade complete

this took like 5 seconds, is it "normal" ? 

but calckey is still on 13.1.4.1

**Comment by lapineige** [comment]
Oh yes, I removed that branch since I gave you the link. Use `https://github.com/YunoHost-Apps/calckey_ynh/tree/testing` instead.

**Comment by benborges** [comment]
Ohh in the main yunohost-apps repo, okay !! thanks :)

**Comment by Zeitverschreib** [comment]
An attempt to upgrade via

`yunohost app upgrade calckey  -u https://github.com/YunoHost-Apps/calckey_ynh/tree/testing`

just failed with

```
Warnung: Here's an extract of the logs before the crash. It might help debugging the error:
Info: DEBUG - .../.pnpm/re2@1.19.0/node_modules/re2 install: gyp http 200 https://nodejs.org/download/release/v19.9.0/node-v19.9.0-headers.tar.gz
Info: DEBUG - .../.pnpm/re2@1.19.0/node_modules/re2 install: gyp http GET https://nodejs.org/download/release/v19.9.0/SHASUMS256.txt
Info: DEBUG - .../.pnpm/re2@1.19.0/node_modules/re2 install: gyp http 500 https://nodejs.org/download/release/v19.9.0/SHASUMS256.txt
Info: DEBUG - .../.pnpm/re2@1.19.0/node_modules/re2 install: gyp WARN install got an error, rolling back install
Info: DEBUG - .../.pnpm/re2@1.19.0/node_modules/re2 install: gyp ERR! configure error
Info: DEBUG - .../.pnpm/re2@1.19.0/node_modules/re2 install: gyp ERR! stack Error: 500  status code downloading checksum
Info: DEBUG - .../.pnpm/re2@1.19.0/node_modules/re2 install: gyp ERR! stack     at downloadShasums (/var/www/calckey/node_modules/.pnpm/node-gyp@9.4.0/node_modules/node-gyp/lib/install.js:306:15)
Info: DEBUG - .../.pnpm/re2@1.19.0/node_modules/re2 install: gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Info: DEBUG - .../.pnpm/re2@1.19.0/node_modules/re2 install: gyp ERR! stack     at async Promise.all (index 1)
Info: DEBUG - .../.pnpm/re2@1.19.0/node_modules/re2 install: gyp ERR! stack     at async go (/var/www/calckey/node_modules/.pnpm/node-gyp@9.4.0/node_modules/node-gyp/lib/install.js:266:7)
Info: DEBUG - .../.pnpm/re2@1.19.0/node_modules/re2 install: gyp ERR! stack     at async install (/var/www/calckey/node_modules/.pnpm/node-gyp@9.4.0/node_modules/node-gyp/lib/install.js:68:18)
Info: DEBUG - .../.pnpm/re2@1.19.0/node_modules/re2 install: gyp ERR! System Linux 5.10.0-22-amd64
Info: DEBUG - .../.pnpm/re2@1.19.0/node_modules/re2 install: gyp ERR! command "/opt/node_n/n/versions/node/19.9.0/bin/node" "/var/www/calckey/node_modules/.pnpm/node-gyp@9.4.0/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
Info: DEBUG - .../.pnpm/re2@1.19.0/node_modules/re2 install: gyp ERR! cwd /var/www/calckey/node_modules/.pnpm/re2@1.19.0/node_modules/re2
Info: DEBUG - .../.pnpm/re2@1.19.0/node_modules/re2 install: gyp ERR! node -v v19.9.0
Info: DEBUG - .../.pnpm/re2@1.19.0/node_modules/re2 install: gyp ERR! node-gyp -v v9.4.0
Info: DEBUG - .../.pnpm/re2@1.19.0/node_modules/re2 install: gyp ERR! not ok
Info: DEBUG - .../.pnpm/re2@1.19.0/node_modules/re2 install: Failed
```

**Comment by lapineige** [comment]
Sounds like a internet issue or an issue on the library repository, you may try again later.

**Comment by Ciechom** [comment]
I upgraded successfully from rc1 to rc3, and it's been stable since 14 hours after the merge to testing branch. Did not test the backup function yet.

**Comment by Ciechom** [comment]
BTW to help with future pull requests, how do you get the sha256 on windows of the upgrade file from the source?

**Comment by benborges** [comment]
upgraded just fine, no issue whatsoever. Amazing !

**Comment by lapineige** [comment]
> BTW to help with future pull requests, how do you get the sha256 on windows of the upgrade file from the source?

The auto-updater should do the trick for normal (non-release candidate) versions :)

Anyway, if you want to compute it, I only know commands line utilities, easy to find online ("sha256sum windows").

**Comment by benborges** [comment]
same on linux : 

`sha256sum /path/to/file > checksum`
`cat checksum`

On WinX you can use Get-FileHash

`Get-FileHash C:\Users\user1\Downloads\file.zip -Algorithm SHA256 | Format-List`

**Pull request merged**
