### PR TITLE
Firefish

### PR DESCRIPTION
**Pull request by ericgaspar**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by lapineige** [comment]
And changing the id just like that is enough ? 🤔
What about the repository name ? 🤔

**Comment by csolisr** [comment]
> And changing the id just like that is enough ? 🤔 What about the repository name ? 🤔

Agree, we would have to move this app to https://github.com/YunoHost-Apps/firefish_ynh

**Comment by lapineige** [comment]
But how do we make sure people's Yunohost will shift to such a new repository ?
By changing the app id + registering the new id in the app catalog ?

**Comment by csolisr** [comment]
> But how do we make sure people's Yunohost will shift to such a new repository ? By changing the app id + registering the new id in the app catalog ?

Unfortunately, yeah. We'd have to make a new app in the catalog, basically. Then we'd have to add a way to migrate data from `calckey_ynh` to `firefish_ynh`. Something similar was made for Vaultwarden when it was renamed from Bitwarden-RS: https://github.com/YunoHost-Apps/vaultwarden_ynh/blob/master/scripts/ynh_handle_app_migration

**Comment by lapineige** [comment]
> Then we'd have to add a way to migrate data from calckey_ynh to firefish_ynh.

Isn't this:

> By changing the app id + registering the new id in the app catalog ?

… doing it ?

**Comment by lapineige** [comment]
So it's like how this will work, we will need a migration script, as you did with the experimental helper. Let's close this PR.

**Comment by lapineige** [comment]
Thanks @ericgaspar :)

**Pull request closed without merging**
