### PR TITLE
Testing : v13.1.2

### PR DESCRIPTION
**Pull request by lapineige**
Merging #12 

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by lapineige** [comment]
It says this branch have conflicts but I have no button to fix them :thinking:

**Comment by oufmilo** [comment]
> It says this branch have conflicts but I have no button to fix them 🤔

Fixed ! ✅

**Comment by ThatOneCalculator** [comment]
Notice: this should be bumped to the 13.1.2 hotfix.

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
@ThatOneCalculator can you confirm we can remove all `.yarn` folder files ?
Yarn is no longer used so we can remove it, right ?
That would save us 500MB, which is quite something.

**Comment by lapineige** [comment]
Upgrade fails on my side from 13.1.1 to 13.1.2.
It seems that it… times out ? :thinking:
> DEBUG - .../cypress@10.11.0/node_modules/cypress postinstall: Cypress 10.11.0 is installed in /var/www/calckey/.cache/Cypress/10.11.0
DEBUG - .../cypress@10.11.0/node_modules/cypress postinstall: Done
DEBUG - .../node_modules/@tensorflow/tfjs-node install: * Building TensorFlow Node.js bindings
DEBUG - .../node_modules/@tensorflow/tfjs-node install: Done
DEBUG - /usr/share/yunohost/helpers.d/user: line 179: 203442 Killed                  sudo -u "$user" "$@"
DEBUG - + ynh_exit_properly

**Comment by ThatOneCalculator** [comment]
> @ThatOneCalculator can you confirm we can remove all `.yarn` folder files ?
> Yarn is no longer used so we can remove it, right ?
> That would save us 500MB, which is quite something.

Yes. Please remove it, as having it can cause problems.

**Comment by lapineige** [comment]
Ok then @oufmilo we should add a migration step with `ynh_secure_remove --file="$final_path/.yarn"` during upgrade.
The thing is, how do we do it during the first upgrade ? I don't remember if it will use the new upgrade script 🤔

I tried something here : https://github.com/YunoHost-Apps/calckey_ynh/pull/16

**Comment by lapineige** [comment]
I tried something here : https://github.com/YunoHost-Apps/calckey_ynh/pull/16

**Comment by oufmilo** [comment]
!testme

**Comment by oufmilo** [comment]
[Test Badge](https://yunorunner.travelpandas.eu/ci/job/18)
[](https://yunorunner.travelpandas.eu/ci/job/18)

**Comment by lapineige** [comment]
Yunohost CI was happy too : https://ci-apps-dev.yunohost.org/ci/job/5582

**Pull request merged**
